### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by UtkuCankaya** [ErenBaygun/v13-Discord-Register#1]
Error: Cannot find module '/home/runner/NNO-REGISTER/index.js'
Require stack:
- /nix/store/9ackq82lagfpsm625fa87k32fsf5gyk2-prybar-nodejs-0.0.0-74f34a6/prybar_assets/nodejs/module-context-hook.js
- /tmp/prybar-nodejs-2149561648.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    
    hatasını almaktayım

**Comment by erenbaygun** [comment]
Discord üzerinden bana ulaşırsan sorunu çözebiliriz.
Sanctus#7296
